[tox]
downloadcache = .tox/_download/
distribute = False
envlist =
    py38-django32
    py{38,39,310,311,312}-django42
skip_missing_interpreters = True

[testenv]
commands =
    python runtests.py
deps =
    django32: Django>=3.2,<4.0
    django42: Django>=4.2,<5.0
